### ISSUE TITLE
[Bug] Fdp crashes everytime i try open my inv or menu 4.3.0

### ISSUE THREAD

**Issue by AwarerX** [opZywl/FDPClient-legacy#111]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<A clear and concise description of what the bug is.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. 
2. 
3. 
4. 

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0-PRE2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- <Example Mod 1.0>

**Additional info**
<Add any other context about the problem here.>

**Comment by AwarerX** [comment]
##########################FDPPROTECT CRASH REPORT##########################

If this problem persists, please send this file to the FDPClient developers! Website (where you can join the discord server): http://FDPClient.Club/
This file will be saved in ".minecraft/FDPCrashLogs.txt"

 | ????????????????????????!  --Apache????
 | Troubleshooting any problem without the error log is like driving with your eyes closed.
 | From Apache official documentation Getting Started chapter
   - INFO:
   |   Version: git-72215de
   |   Time: 1655190986189
   |   OS: WINDOWS

##########################FDPPROTECT CRASH REPORT##########################
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-72215de (1).jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 14/06/22 5:16 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:807)
	at net.optifine.shaders.ShadersRender.renderItemFP(ShadersRender.java:223)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1062)
	at net.optifine.shaders.ShadersRender.renderHand0(ShadersRender.java:161)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1875)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1587)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:807)
	at net.optifine.shaders.ShadersRender.renderItemFP(ShadersRender.java:223)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1062)
	at net.optifine.shaders.ShadersRender.renderHand0(ShadersRender.java:161)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1875)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1587)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Awarer'/224733, l='MpServer', x=0.52, y=124.00, z=-24.27]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,124.00,-26.00 - World: (0,124,-26), Chunk: (at 0,7,6 in 0,-2; contains blocks 0,0,-32 to 15,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 880708906 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Awarer'/224733, l='MpServer', x=0.52, y=124.00, z=-24.27]]
	Retry entities: 0 total; []
	Server brand: UniversoCraft
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 201902200 bytes (192 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-72215de (1).jar)

**Comment by AwarerX** [comment]
ive got it by opening menus in universocraft and if you try open skywars up in bmc it will crash too

**Comment by FallenCrystal** [comment]
i didnt have any problems using it myself.
but ive seen "Silent" with ChestStealer on some people crash

**Comment by ghost** [comment]
Stop using FDPClient, start using LiquidBounce with scripts.
