### ISSUE TITLE
[Bug] crash

### ISSUE THREAD

**Issue by gangmaster-dev** [opZywl/FDPClient-legacy#124]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
game crash

**To Reproduce**
1. launch the game
2. go to multiplayer
3. join to a server

**Expected behavior**
when you launch the game, and joins to the server it carshes

**Crash Report**
If your game crashed, please paste your crash report below.

```text
// I let you down. Sorry :(

Time: 6/16/22 7:06 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:721)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:782)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1415)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1058)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:721)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:782)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1415)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)

-- Affected level --
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
TransformerLoader (FDPClient-72215de.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: latest build v4.3.0

**Comment by rafi67000** [comment]
i have the same problem

**Comment by justkevinyt11** [comment]
I got same issue

**Comment by opZywl** [comment]
fix. use latest actions
