### ISSUE TITLE
[Bug] <fix crash on PojavLauncher>

### ISSUE THREAD

**Issue by ImXlanzCrd** [opZywl/FDPClient-legacy#133]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<A clear and concise description of what the bug is.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. 
2. 
3. 
4. 

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-38591b3.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 22/06/17 03:31
Description: Initializing game

java.lang.RuntimeException: glCheckFramebufferStatus returned unknown status:0
	at net.minecraft.client.shader.Framebuffer.func_147611_b(Framebuffer.java:178)
	at net.minecraft.client.shader.Framebuffer.func_147613_a(Framebuffer.java:59)
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:39)
	at net.minecraft.client.LoadingScreenRenderer.<init>(LoadingScreenRenderer.java:41)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:510)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.shader.Framebuffer.func_147611_b(Framebuffer.java:178)
	at net.minecraft.client.shader.Framebuffer.func_147613_a(Framebuffer.java:59)
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:39)
	at net.minecraft.client.LoadingScreenRenderer.<init>(LoadingScreenRenderer.java:41)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:510)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (aarch64) version Android-11
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 561468600 bytes (535 MB) / 1017643008 bytes (970 MB) up to 1017643008 bytes (970 MB)
	JVM Flags: 3 total; -Xms1040M -Xmx1040M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-38591b3.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'vgpu' Version: '3.0' Renderer: 'vgpu 1.3.68'
	Launched Version: 1.8.9
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: vgpu 1.3.68 GL version 3.0, vgpu
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Celeste 16x Cotton Candy.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x null
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 3
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0
	OpenGlRenderer: vgpu 1.3.68
	OpenGlVendor: vgpu
	CpuCount: 8
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0-PRE2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- <Example Mod 1.0>

**Additional info**
<Add any other context about the problem here.>

**Comment by TheMosKau** [comment]
shader bg is being weird on pojav

**Comment by hackerlod123** [comment]
OS : Android 10
Minecraft 1.8.9
Forge 11.15.1.2318
FDP CLIENT 4.3.0-20220619-2

App / Game exited with code 1

**Comment by hackerlod123** [comment]
![Uploading Screenshot_20220619_232928.jpg…]()

**Comment by ghost** [comment]
Stop using FDPClient, start using LiquidBounce with scripts.
