### ISSUE TITLE
[Bug] Crash on server join

### ISSUE THREAD

**Issue by MarkGG8181** [opZywl/FDPClient-legacy#141]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Whenever I join any server with book plugin, I login it sends me to the main server but then it crashes.

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Join any server with some book plugin
2. Login/Register
3. When it shows the book gui it crashes
4. Minecraft closes and opens FDP crash report

**Expected behavior**
I expected to login in a server normally without it crashing.

**Screenshots/Video**
![Screenshot_3](https://user-images.githubusercontent.com/86848614/174246931-34476b35-3bd2-4f0f-a5df-94d7b1702c19.png)

**Crash Report**
If your game crashed, please paste your crash report below.

```text
##########################FDPPROTECT CRASH REPORT##########################

If this problem persists, please send this file to the FDPClient developers! Website (where you can join the discord server): http://FDPClient.Club/
This file will be saved in ".minecraft/FDPCrashLogs.txt"

 | 在没有错误日志的情况下诊断任何问题无异于闭眼开车!  --Apache官方文档
 | Troubleshooting any problem without the error log is like driving with your eyes closed.
 | From Apache official documentation Getting Started chapter
   - INFO:
   |   Version: git-72215de
   |   Time: 1655450279911
   |   OS: WINDOWS

##########################FDPPROTECT CRASH REPORT##########################
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-72215de.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 6/17/22 10:17 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:721)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:782)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1415)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1058)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at misc.tweaker.Tweaker.a(Unknown Source)
	at misc.tweaker.Tweaker.stubMain(Unknown Source)
	at misc.tweaker.StubMain.main(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:721)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:782)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1415)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)

-- Affected level --
Details:
	Level name: MpServer
	All players: 10 total; [EntityPlayerSP['Labrencis'/36269, l='MpServer', x=0.50, y=90.00, z=4.50], EntityOtherPlayerMP['§r'/608, l='MpServer', x=7.50, y=90.00, z=1.50], EntityOtherPlayerMP['Rodagave115'/584, l='MpServer', x=3.66, y=111.50, z=17.97], EntityOtherPlayerMP['§rBotervrij'/587, l='MpServer', x=3.63, y=111.50, z=24.00], EntityOtherPlayerMP['§rJustThiemo'/590, l='MpServer', x=3.47, y=111.50, z=20.97], EntityOtherPlayerMP['Andeh'/581, l='MpServer', x=-2.47, y=111.50, z=23.94], EntityOtherPlayerMP['§rvoodootje0'/593, l='MpServer', x=-2.59, y=111.50, z=18.00], EntityOtherPlayerMP['§rGunfire'/596, l='MpServer', x=-2.50, y=111.50, z=20.97], EntityOtherPlayerMP['§r'/599, l='MpServer', x=0.50, y=93.06, z=36.47], EntityOtherPlayerMP['§r'/605, l='MpServer', x=2.59, y=87.00, z=-16.41]]
	Chunk stats: MultiplayerChunkCache: 30, 30
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,90.00,0.00 - World: (0,90,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 542980971 game time, 4297200 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 67 total; [EntityItemFrame['entity.ItemFrame.name'/129, l='MpServer', x=0.50, y=88.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/130, l='MpServer', x=0.50, y=87.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/131, l='MpServer', x=3.50, y=89.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/132, l='MpServer', x=1.50, y=90.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/133, l='MpServer', x=2.50, y=90.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/134, l='MpServer', x=1.50, y=88.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/135, l='MpServer', x=0.50, y=89.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/136, l='MpServer', x=2.50, y=88.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/137, l='MpServer', x=0.50, y=90.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/138, l='MpServer', x=3.50, y=87.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/139, l='MpServer', x=2.50, y=89.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/140, l='MpServer', x=3.50, y=90.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/141, l='MpServer', x=1.50, y=89.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/142, l='MpServer', x=3.50, y=88.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/143, l='MpServer', x=1.50, y=87.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/144, l='MpServer', x=2.50, y=87.50, z=-16.97], EntityPlayerSP['Labrencis'/36269, l='MpServer', x=0.50, y=90.00, z=4.50], EntityArmorStand['Armor Stand'/542, l='MpServer', x=7.50, y=94.47, z=1.50], EntityArmorStand['§6Gold Shop§f is a global currency.'/543, l='MpServer', x=7.50, y=94.22, z=1.50], EntityArmorStand['§fWith this currency, you have an in-game Store'/544, l='MpServer', x=7.50, y=93.97, z=1.50], EntityArmorStand['§fwhere you can buy goods such as §dRanks§f, §9Boosters§f,'/545, l='MpServer', x=7.50, y=93.72, z=1.50], EntityArmorStand['nd more using §6Gold§f which is to be'/546, l='MpServer', x=7.50, y=93.47, z=1.50], EntityArmorStand['§fbought on our Store.'/547, l='MpServer', x=7.50, y=93.22, z=1.50], EntityArmorStand['Armor Stand'/548, l='MpServer', x=7.50, y=92.97, z=1.50], EntityArmorStand['§fMake sure to purchase your §6Gold§f'/549, l='MpServer', x=7.50, y=92.72, z=1.50], EntityArmorStand['§fon our Store : §estore.jartexnetwork.com'/550, l='MpServer', x=7.50, y=92.47, z=1.50], EntityOtherPlayerMP['§r'/608, l='MpServer', x=7.50, y=90.00, z=1.50], EntityArmorStand['Armor Stand'/551, l='MpServer', x=7.50, y=92.22, z=1.50], EntityOtherPlayerMP['Rodagave115'/584, l='MpServer', x=3.66, y=111.50, z=17.97], EntityArmorStand['§6§lGold Shop'/552, l='MpServer', x=7.50, y=91.97, z=1.50], EntityOtherPlayerMP['§rBotervrij'/587, l='MpServer', x=3.63, y=111.50, z=24.00], EntityArmorStand['§a§lRight Click§r§f to browse open'/553, l='MpServer', x=7.50, y=91.72, z=1.50], EntityOtherPlayerMP['§rJustThiemo'/590, l='MpServer', x=3.47, y=111.50, z=20.97], EntityOtherPlayerMP['Andeh'/581, l='MpServer', x=-2.47, y=111.50, z=23.94], EntityOtherPlayerMP['§rvoodootje0'/593, l='MpServer', x=-2.59, y=111.50, z=18.00], EntityOtherPlayerMP['§rGunfire'/596, l='MpServer', x=-2.50, y=111.50, z=20.97], EntityOtherPlayerMP['§r'/599, l='MpServer', x=0.50, y=93.06, z=36.47], EntityOtherPlayerMP['§r'/605, l='MpServer', x=2.59, y=87.00, z=-16.41], EntityItemFrame['entity.ItemFrame.name'/65, l='MpServer', x=-0.50, y=90.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/66, l='MpServer', x=-0.50, y=87.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/67, l='MpServer', x=-1.50, y=90.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/68, l='MpServer', x=-2.50, y=88.50, z=-16.97], EntityOtherPlayerMP['Andeh'/581, l='MpServer', x=-2.47, y=111.50, z=23.94], EntityItemFrame['entity.ItemFrame.name'/69, l='MpServer', x=-2.50, y=89.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/70, l='MpServer', x=-0.50, y=88.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/71, l='MpServer', x=-1.50, y=88.50, z=-16.97], EntityOtherPlayerMP['Rodagave115'/584, l='MpServer', x=3.66, y=111.50, z=17.97], EntityItemFrame['entity.ItemFrame.name'/72, l='MpServer', x=-1.50, y=89.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/73, l='MpServer', x=-2.50, y=87.50, z=-16.97], EntityItemFrame['entity.ItemFrame.name'/74, l='MpServer', x=-0.50, y=89.50, z=-16.97], EntityOtherPlayerMP['§rBotervrij'/587, l='MpServer', x=3.63, y=111.50, z=24.00], EntityItemFrame['entity.ItemFrame.name'/75, l='MpServer', x=-2.50, y=90.50, z=-16.97], EntityArmorStand['§e§lDuck Hunt'/42828, l='MpServer', x=-17.00, y=88.09, z=-103.50], EntityItemFrame['entity.ItemFrame.name'/76, l='MpServer', x=-1.50, y=87.50, z=-16.97], EntityArmorStand['§fSit back, relax and'/42829, l='MpServer', x=-17.00, y=87.84, z=-103.50], EntityArmorStand['§fcatch some ducks!'/42830, l='MpServer', x=-17.00, y=87.63, z=-103.50], EntityOtherPlayerMP['§rJustThiemo'/590, l='MpServer', x=3.47, y=111.50, z=20.97], EntityArmorStand['§fWill you catch the most?'/42831, l='MpServer', x=-17.00, y=87.41, z=-103.50], EntityArmorStand['§fActive hunters: §60'/42832, l='MpServer', x=-17.00, y=86.94, z=-103.50], EntityArmorStand['§fDucks caught: §60'/42833, l='MpServer', x=-17.00, y=86.72, z=-103.50], EntityOtherPlayerMP['§rvoodootje0'/593, l='MpServer', x=-2.59, y=111.50, z=18.00], EntityArmorStand['§6play.jartexnetwork.com'/42834, l='MpServer', x=-17.00, y=86.25, z=-103.50], EntityOtherPlayerMP['§rGunfire'/596, l='MpServer', x=-2.50, y=111.50, z=20.97], EntityOtherPlayerMP['§r'/599, l='MpServer', x=0.50, y=93.06, z=36.47], EntityOtherPlayerMP['§r'/605, l='MpServer', x=2.59, y=87.00, z=-16.41], EntityOtherPlayerMP['§r'/608, l='MpServer', x=7.50, y=90.00, z=1.50], EntityRabbit['Rabbit'/42484, l='MpServer', x=-2.03, y=90.00, z=3.19]]
	Retry entities: 0 total; []
	Server brand: Waterfall <- PaperSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at misc.tweaker.Tweaker.a(Unknown Source)
	at misc.tweaker.Tweaker.stubMain(Unknown Source)
	at misc.tweaker.StubMain.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 903321472 bytes (861 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 13 total; -Xverify:none -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Xms2048M -Xmx2048M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-72215de.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4703' Renderer: 'Intel(R) HD Graphics 5500'
	Launched Version: Forge 1.8.9
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.4703, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
```

**System Information**
 - OS: Windows 11
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: FDPClient-72215de

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- No only FDP

**Additional info**
None

**Comment by afdera** [comment]
FDPClient MixinEntityPlayerSP.java and  MixinEntityLivingBase.java Bug

**Comment by MarkGG8181** [comment]
> FDPClient MixinEntityPlayerSP.java and MixinEntityLivingBase.java Bug

How do I fix this?

**Comment by afdera** [comment]
Failure to fix requires waiting for the author to fix the source code

**Comment by MarkGG8181** [comment]
> Failure to fix requires waiting for the author to fix the source code

Okay, does this bug only happen to me?

**Comment by afdera** [comment]
What won't happen is that there will be serious bugs in this release, including breaking into single-player and multi-player Worlds

**Comment by afdera** [comment]
Wait patiently for the FDPCLIENT fix

**Comment by GutatOderSo** [comment]
for me it fixes it when i press escape when joining a server or singleplayer.
i didnt know it was about boooks so nvm

**Comment by DinoFengz** [comment]
custom Build?

**Comment by MatrixU5er** [comment]
可能是某个模块导致的，你可以尝试在cfg文件中关闭那个模块 - It may be caused by a module. You can try to close that module in the cfg file
#

**Comment by contionability** [comment]
用新版本

**Comment by contionability** [comment]
这个问题是Mixin导致的
我已经把出问题的Commits全部Reversed
（Caused By opZywl）

**Comment by contionability** [comment]
对了
这个crash会覆盖你的Killaura配置（idk why, that‘s wired）
所以你得注意一下别进服直接开飘然后封了

**Comment by playeur242** [comment]
it keep happening to me too

**Comment by ghost** [comment]
Stop using FDPClient, start using LiquidBounce with scripts.
