### ISSUE TITLE
[Bug] Join server = Crash

### ISSUE THREAD

**Issue by tofutofu102** [opZywl/FDPClient-legacy#205]
**Describe the bug**
Suddenly Client started to Crash. It was working normally until yesterday; disabling Visual systems (ESP, etc.) did not solve the problem.

**To Reproduce**
1. Join Single(or Server)

**Expected behavior**
I hope you don't do Crash.

**Screenshots/Video**
None

**Crash Report**
```text
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (WWEs-altening-mod-1.8.9-forge.jar)
  TransformerLoader (FDPClient-4.3.0-20220619-2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 22/06/21 7:57
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.EntityLivingBase.func_70664_aZ(EntityLivingBase.java:2205)
	at net.minecraft.entity.player.EntityPlayer.func_70664_aZ(EntityPlayer.java:1660)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1794)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:544)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1234)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1614)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:117)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.World.func_72870_g(World.java:1831)
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.EntityLivingBase.func_70664_aZ(EntityLivingBase.java:2205)
	at net.minecraft.entity.player.EntityPlayer.func_70664_aZ(EntityPlayer.java:1660)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1794)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:544)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1234)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1614)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:117)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.World.func_72870_g(World.java:1831)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 211
	Entity Name: Rainbow_dash1103
	Entity's Exact location: -26.69, 73.00, 98.20
	Entity's Block location: -27.00,73.00,98.00 - World: (-27,73,98), Chunk: (at 5,4,2 in -2,6; contains blocks -32,0,96 to -17,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.14, 0.42, 0.07
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1663)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Rainbow_dash1103'/211, l='MpServer', x=-26.69, y=73.00, z=98.20]]
	Chunk stats: MultiplayerChunkCache: 224, 224
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -32.00,64.00,248.00 - World: (-32,64,248), Chunk: (at 0,4,8 in -2,15; contains blocks -32,0,240 to -17,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 7265 game time, 7265 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 40 total; [EntityCreeper['Creeper'/128, l='MpServer', x=30.59, y=46.00, z=109.00], EntityBat['Bat'/524, l='MpServer', x=-73.25, y=46.00, z=123.78], EntityBat['Bat'/911, l='MpServer', x=0.15, y=60.47, z=87.56], EntityCreeper['Creeper'/784, l='MpServer', x=24.50, y=34.00, z=118.50], EntityBat['Bat'/914, l='MpServer', x=29.88, y=19.00, z=95.71], EntityZombie['Zombie'/673, l='MpServer', x=1.50, y=16.00, z=127.50], EntitySkeleton['Skeleton'/947, l='MpServer', x=38.50, y=19.00, z=131.50], EntitySkeleton['Skeleton'/822, l='MpServer', x=-98.50, y=19.00, z=157.69], EntitySkeleton['Skeleton'/57, l='MpServer', x=-99.50, y=12.00, z=121.50], EntitySkeleton['Skeleton'/699, l='MpServer', x=27.44, y=10.00, z=143.16], EntityZombie['Zombie'/702, l='MpServer', x=-78.50, y=20.00, z=35.50], EntitySkeleton['Skeleton'/958, l='MpServer', x=23.50, y=26.00, z=32.50], EntityCow['Cow'/66, l='MpServer', x=-82.53, y=70.00, z=114.44], EntityCow['Cow'/67, l='MpServer', x=-83.50, y=73.00, z=119.53], EntityCreeper['Creeper'/68, l='MpServer', x=-84.13, y=13.00, z=130.78], EntityWolf['Wolf'/73, l='MpServer', x=-65.31, y=63.00, z=86.47], EntityCow['Cow'/74, l='MpServer', x=-70.75, y=62.25, z=90.63], EntityCow['Cow'/76, l='MpServer', x=-69.47, y=63.00, z=91.50], EntityWolf['Wolf'/77, l='MpServer', x=-65.50, y=63.00, z=87.69], EntityCow['Cow'/78, l='MpServer', x=-66.47, y=64.00, z=91.50], EntityCow['Cow'/79, l='MpServer', x=-67.63, y=64.00, z=89.91], EntitySkeleton['Skeleton'/81, l='MpServer', x=-74.72, y=14.00, z=118.50], EntityBat['Bat'/82, l='MpServer', x=-75.50, y=16.10, z=116.72], EntityPlayerSP['Rainbow_dash1103'/211, l='MpServer', x=-26.69, y=73.00, z=98.20], EntityZombie['Zombie'/84, l='MpServer', x=-78.47, y=45.00, z=123.78], EntityCow['Cow'/85, l='MpServer', x=-76.56, y=70.00, z=117.50], EntityCow['Cow'/86, l='MpServer', x=-79.50, y=71.00, z=116.53], EntityCreeper['Creeper'/217, l='MpServer', x=27.50, y=25.00, z=19.50], EntityBat['Bat'/607, l='MpServer', x=-95.72, y=19.10, z=164.19], EntityZombie['Zombie'/98, l='MpServer', x=-35.47, y=27.00, z=108.94], EntitySkeleton['Skeleton'/101, l='MpServer', x=-29.50, y=34.00, z=91.50], EntityWolf['Wolf'/102, l='MpServer', x=-19.31, y=63.00, z=112.47], EntityBat['Bat'/488, l='MpServer', x=29.85, y=18.04, z=35.20], EntitySkeleton['Skeleton'/872, l='MpServer', x=6.69, y=52.00, z=98.88], EntityCreeper['Creeper'/877, l='MpServer', x=-94.50, y=15.00, z=146.50], EntityZombie['Zombie'/110, l='MpServer', x=-5.16, y=19.00, z=150.47], EntityZombie['Zombie'/112, l='MpServer', x=1.28, y=55.41, z=77.28], EntityItem['item.item.rottenFlesh'/113, l='MpServer', x=1.13, y=55.00, z=77.13], EntitySkeleton['Skeleton'/885, l='MpServer', x=-90.50, y=20.00, z=34.50], EntityZombie['Zombie'/635, l='MpServer', x=-38.38, y=49.00, z=121.38]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 298386448 bytes (284 MB) / 805306368 bytes (768 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
MixinLoader (WWEs-altening-mod-1.8.9-forge.jar)
  
TransformerLoader (FDPClient-4.3.0-20220619-2.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.95' Renderer: 'NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.95, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz
```

**System Information**
 - OS: Windows10 64bit 21h1
 - Minecraft Version: 1.8.9
 - Forge Version: 1.8.9 11.15.1.2318
 - FDPClient Version: Build - 20220619-2

**Other Installed Mods**
- WWEs-altening-mod-1.8.9-forge.jar

**Additional info**
We use DeepL translation. Due to mistranslation, the text may be unnatural and difficult to read.

**Comment by contionability** [comment]
Don't use other mods
idk why it crashes with other mods
(except ViaVersion)

**Comment by aftercares0** [comment]
i need via versions and optifine
bc to hack on 1.12.2 server
(also why tf it crash xd)

**Comment by DinoFengz** [comment]
java.lang.NullPointerException: Ticking entity
bug

**Comment by ClassicSenior** [comment]
> i need via versions and optifine bc to hack on 1.12.2 server (also why tf it crash xd)

Suck my dick... Its not a utility client idiot

**Comment by ghost** [comment]
Stop using FDPClient, start using LiquidBounce with scripts.

**Comment by ghost** [comment]
same
