### ISSUE TITLE
[Bug] Crash after joining server

### ISSUE THREAD

**Issue by L1bws** [opZywl/FDPClient-legacy#226]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
进服就崩溃，可能可以启动一次，但是第二次启动后一进服直接崩溃
(Crash, it crashes when you enter the server, it may be possible to start it once, but after the second startup, it crashes directly after entering the server)

**To Reproduce**
1. 正常安装FDPClient Mod (Install FDPClient Mod as normal)
2. 第一次正常启动 (The first normal start)
3. 第二次在载入模块的时候出现"[Client thread/ERROR]: Failed to load module: net.ccbluex.liquidbounce.features.module.modules.combat.KillAura (java.lang.NullPointerException: null cannot be cast to non-null type net.ccbluex.liquidbounce.features.module.modules.movement.TargetStrafe)" (The second time it appears when loading the module "[Client thread/ERROR]: Failed to load module: net.ccbluex.liquidbounce.features.module.modules.combat.KillAura (java.lang.NullPointerException: null cannot be cast to non-null type net.ccbluex.liquidbounce.features.module.modules.movement.TargetStrafe)")
4. 进服直接崩溃 (Crash directly into the server)
5. 继续第3和第4步 (Continue with steps 3 and 4)

**Expected behavior**
首先，第一次或第二次启动后，我的KillAura配置不会被直接从配置里删除，其次不应该在进入服务器的时候直接崩溃
(First of all, after the first or second boot, my KillAura configuration will not be deleted directly from the configuration, and secondly it should not crash directly when entering the server)

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.
Mods安装列表 (Mods installation list)：![image](https://user-images.githubusercontent.com/51532767/175277616-5ffadb11-40f7-4c41-9c1a-2806502a2293.png)
最后的HMCL日志 (Last HMCL log)：![image](https://user-images.githubusercontent.com/51532767/175278134-23c0e5bf-59b2-4df6-be73-af9667b37757.png)
崩溃日志 (crash log)：![image](https://user-images.githubusercontent.com/51532767/175278201-3d2795fc-3e35-4e99-8d27-4f719ac3fa52.png)

**Crash Report**
If your game crashed, please paste your crash report below.

```text
######################### FDP CRASH REPORT #########################

If this problem persists, please send this file to the FDPClient developers! Website (where you can join the discord server): http://FDPClient.Club/
This file will be saved in ".minecraft/FDPCrashLogs.txt"

 | 在没有错误日志的情况下诊断任何问题无异于闭眼开车!  --Apache官方文档
 | Troubleshooting any problem without the error log is like driving with your eyes closed.
 | From Apache official documentation Getting Started chapter
   - INFO:
   |   Version: git-ab1349d
   |   Time: 1655979309770
   |   OS: WINDOWS

######################### FDP CRASH REPORT #########################
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-4.3.0-20220619-2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 22-6-23 下午6:15
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:807)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1065)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:1009)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1950)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1587)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:807)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1065)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:1009)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1950)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1587)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['FuckAntiCheat'/615, l='MpServer', x=82.14, y=63.00, z=-44.25]]
	Chunk stats: MultiplayerChunkCache: 40, 40
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -21.00,64.00,-130.00 - World: (-21,64,-130), Chunk: (at 11,4,14 in -2,-9; contains blocks -32,0,-144 to -17,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1962220 game time, 118198 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 26 total; [EntityPlayerSP['FuckAntiCheat'/615, l='MpServer', x=82.14, y=63.00, z=-44.25], EntityCreeper['爬行者'/129, l='MpServer', x=77.50, y=68.00, z=-74.50], EntitySpider['蜘蛛'/133, l='MpServer', x=80.69, y=68.00, z=-82.69], EntitySpider['蜘蛛'/134, l='MpServer', x=84.50, y=66.00, z=-82.50], EntitySpider['蜘蛛'/135, l='MpServer', x=91.66, y=69.00, z=-19.69], EntitySpider['蜘蛛'/136, l='MpServer', x=94.97, y=69.00, z=-20.72], EntityCreeper['爬行者'/144, l='MpServer', x=97.50, y=70.00, z=-24.50], EntitySpider['蜘蛛'/145, l='MpServer', x=98.50, y=70.00, z=-27.50], EntityCreeper['爬行者'/146, l='MpServer', x=105.50, y=70.00, z=-6.50], EntityCreeper['爬行者'/608, l='MpServer', x=59.50, y=49.00, z=-12.50], EntityRabbit['兔子'/617, l='MpServer', x=113.59, y=67.00, z=-80.31], EntityRabbit['兔子'/618, l='MpServer', x=128.53, y=67.00, z=-78.53], EntityCreeper['爬行者'/110, l='MpServer', x=38.50, y=18.00, z=-81.50], EntitySpider['蜘蛛'/111, l='MpServer', x=34.50, y=66.00, z=-79.50], EntitySpider['蜘蛛'/112, l='MpServer', x=43.50, y=66.00, z=-68.50], EntityCreeper['爬行者'/113, l='MpServer', x=36.59, y=65.00, z=-76.03], EntityZombie['僵尸'/114, l='MpServer', x=42.50, y=28.00, z=-63.50], EntityChicken['鸡'/115, l='MpServer', x=44.47, y=61.00, z=-54.38], EntityRabbit['兔子'/116, l='MpServer', x=45.47, y=61.00, z=-54.91], EntityPig['猪'/118, l='MpServer', x=61.13, y=77.00, z=-74.41], EntityCreeper['爬行者'/119, l='MpServer', x=56.50, y=67.00, z=-67.50], EntityZombie['僵尸'/120, l='MpServer', x=56.53, y=80.00, z=-79.59], EntityCreeper['爬行者'/122, l='MpServer', x=57.50, y=69.00, z=-4.50], EntityZombie['僵尸'/125, l='MpServer', x=73.34, y=77.00, z=-90.66], EntityCreeper['爬行者'/126, l='MpServer', x=79.34, y=68.00, z=-83.09], EntityZombie['僵尸'/127, l='MpServer', x=69.50, y=84.00, z=-88.50]]
	Retry entities: 0 total; []
	Server brand: PaperSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_331, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 544075032 bytes (518 MB) / 1073741824 bytes (1024 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx16384m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-4.3.0-20220619-2.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13413 Compatibility Profile Context FireGL 15.201.2401.1010' Renderer: 'ATI FirePro V (FireGL V) Graphics Adapter'
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: ATI FirePro V (FireGL V) Graphics Adapter GL version 4.5.13413 Compatibility Profile Context FireGL 15.201.2401.1010, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor 
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13413 Compatibility Profile Context FireGL 15.201.2401.1010
	OpenGlRenderer: ATI FirePro V (FireGL V) Graphics Adapter
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 16
```

**System Information**
 - OS: Windows 11
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: 4.3.0 PREE-2.1[4.3.0-20220619-2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- 我并没安装任何除FDPClient以外的模组
- (I don't have any mods installed other than FDPClient)

**Additional info**
如果我安装了一些别的不兼容的模组，那么第一次启动客户端时KillAura配置就会被直接从配置里删除，并且在进入服务器的时候崩溃
(If I install some other incompatible mod, the KillAura config is removed directly from the config the first time I start the client, and crashes when entering the server)
如果我只安装了FDPClient，那么第二次启动客户端时KillAura配置就会被直接从配置里删除，并且在进入服务器的时候崩溃
(If I only install FDPClient, the KillAura config is removed directly from the config the second time I start the client, and crashes when entering the server)
无论清空配置还是手动重写配置都会出现上面两种中的一种情况
(One of the above two situations will occur whether you clear the configuration or manually rewrite the configuration)

**Comment by contionability** [comment]
草
终于有一个正常报Error的issue了
thx让我找到了crash的真正原因

**Comment by L1bws** [comment]
> 草 终于有一个正常报Error的issue了 thx让我找到了crash的真正原因

很奇怪，哪怕我直接用fdp生成的默认配置，为什么就正好只有KillAura的配置会被从载入的配置中删除；是KillAura模块出现了问题还是我电脑配置的问题？🤔

**Comment by L1bws** [comment]
> 草 终于有一个正常报Error的issue了 thx让我找到了crash的真正原因

也许我应该试试[build #294](https://github.com/UnlegitMC/FDPClient/actions/runs/2548697836)？🤔

**Comment by L1bws** [comment]
> > 草 终于有一个正常报Error的issue了 thx让我找到了crash的真正原因
> 
> 也许我应该试试[build #294](https://github.com/UnlegitMC/FDPClient/actions/runs/2548697836)？🤔

![image](https://user-images.githubusercontent.com/51532767/175385393-50a82ce6-1012-4fd7-9c73-9ff54dcbbd1f.png)
我成功载入FDP和多个其它模组后，成功多次运行客户端，并使用配置进入服务器
也许。。。修好了？🤔

**Comment by contionability** [comment]
Killaura调用了TargetStrafe
但是TargetStrafe比Killaura晚加载
导致Killaura出现了NullException
然后Killaura模块加载失败
就导致崩端+配置重置

**Comment by L1bws** [comment]
> Killaura调用了TargetStrafe 但是TargetStrafe比Killaura晚加载 导致Killaura出现了NullException 然后Killaura模块加载失败 就导致崩端+配置重置

OK
