### ISSUE TITLE
[Bug] <Title Here>

### ISSUE THREAD

**Issue by HarcicYang** [opZywl/FDPClient-legacy#236]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<A clear and concise description of what the bug is.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Put FDPLoader-v4.2.1.jar to mods folder
2. Launch Minecraft
3. Minecraft launch failed

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[authlib-injector] [INFO] Logging file: D:\应用\BakaXL\.minecraft\versions\1.8.9-forge1.8.9-11.15.1.2318\authlib-injector.log
[authlib-injector] [INFO] Version: 1.1.45
[authlib-injector] [INFO] Authentication server: http://localhost:41812/yggdrasil/
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
[authlib-injector] [DEBUG] Metadata: {"meta":{"serverName":"BakaXL","implementationName":"BakaXL Network SkinShare \u76AE\u80A4\u5999\u4EAB","implementationVersion":"3.2.1.0","links":{"homepage":"https://www.BakaXL.com/","register":"https://account.BakaXL.com/","login":"https://account.BakaXL.com/"},"feature.non_email_login":false,"feature.legacy_skin_api":false,"feature.no_mojang_namespace":true,"feature.enable_mojang_anti_features":false,"feature.privileges_api":false,"feature.enable_profile_key":true},"skinDomains":["localhost","127.0.0.1"],"signaturePublickey":"-----BEGIN PUBLIC KEY-----MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqLilI+0MyU+BVxjgFm3XJoKONGyBHtU/PNmrrj55XANgTA0r0Gz1dwHkaxYiEEidx9YTLWzfcJwEBWQ80s26FQEHUBpvRnnhoZFWprz6uYZ6uzuXzACAKtSwlnq/KtuOV5czd73EFaDRq2YKrpJx9eOLJTuPyMh2JVkLX/yQKYwBCQ7TsQCPkT+f/ncr68YDCcsP3gr3AGzbgV+4ZS+zMbtrmvtIlnUw+jes40Gobid7UZLSLZVlbS3wXJAJznNRm53qTDr9YKTL+UHBMQBh/MgBcx9WewnkEbasWLki99iZ4/inkiEXnkbGEam2YCOr4+SVJGaBBVZGw97VpUutzYvZZzP4ZOW2m6+qw3F5dU52Uq4yyL//E4Ui/4MyfwUt4tjLH1gYOPP6Sy8bJTzQupewdKAoCe2SU5LPCdCNQs+fqSJVQa5lWqVqNbFdkq6TMxFNfQa/afoOPvpudb07DSDTfLsLGfILKobhlUg6DYr7nRp2gaff8ExXYsspEvgOc7EcNLagnWJYnhaZX2JzJByL+rIRBfAtj7x16ZLai3a7FWQ52eVk62Jvx92imBhdedVJE4gzI57X3rpp0bDnoKrdmWyiHc8DplHArQY3yRDxKO0Vljht5V8CxnfLUhwfHRWhxEDsFEFEUnX1Eki0JXX+GblMRxOSila1aPeG9PkCAwEAAQ==-----END PUBLIC KEY-----","TargetServerRoot":null}
[authlib-injector] [DEBUG] Parsed metadata: APIMetadata [apiRoot=http://localhost:41812/yggdrasil/, skinDomains=[localhost, 127.0.0.1], decodedPublickey=Optional[Sun RSA public key, 4096 bits
  params: null
  modulus: 688322727657904121777898421808212983382357977818436918850687259746411121850433623279424106572769374978331672448408736551093989054538556899538264895821945829165667675428226431307591892069573606466609409515328732554841317019711706446146459980848518882071706271874460148879724846063352287447275457685357065403074396608649328561614250531790793691146986756684244525695252290184034632296436276518084339182708717595069064563287568846902642941684419340246511969584298793155748533405589704157846879541126186818492508956741344284234222458546552088390857104149306404713784864125530639805085333069447260366884871566761964158462319852617768853958158931733164145567354498925945126738873793649678297775508565724431315041214344330374715278650770394278468248770543740737272874205372471538211556252307374573088900047646995851150127457478030409015744644575867021366734756204197802007571801731713018476579104971912812671997440994796974688086999482435023021183407826562131051744190085430829040986466775928086129670965933389430856321547333966907468126575463134855141164645123821835950761454249221454348127677275310315670587381175887627328322921467265501721780727857630403847559111831766793181979339394301146130139057451476062110737814726142014531117184249
  public exponent: 65537], meta={feature.enable_mojang_anti_features=false, feature.enable_profile_key=true, feature.legacy_skin_api=false, feature.no_mojang_namespace=true, feature.non_email_login=false, feature.privileges_api=false, implementationName=BakaXL Network SkinShare 皮肤妙享, implementationVersion=3.2.1.0, links={"homepage":"https:\/\/www.BakaXL.com\/","register":"https:\/\/account.BakaXL.com\/","login":"https:\/\/account.BakaXL.com\/"}, serverName=BakaXL}]
[authlib-injector] [INFO] Disabled Mojang namespace
[14:42:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:42:12] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:42:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[14:42:12] [main/INFO] [FML]: Forge Mod Loader version 11.15.1.2318 for Minecraft 1.8.9 loading
[14:42:12] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_333, running on Windows 11:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_333
[14:42:12] [main/WARN] [FML]: The coremod customskinloader.forge.ForgePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:42:12] [main/INFO] [FML]: Loading tweaker cn.xigua.FDPLoader.MixinTweaker from FDPLoader-v4.2.1.jar
[14:42:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:42:12] [main/INFO] [LaunchWrapper]: Loading tweak class name cn.xigua.FDPLoader.MixinTweaker
[authlib-injector] [WARNING] Failed to transform [cn/xigua/FDPLoader/MixinTweaker]
java.lang.ArrayIndexOutOfBoundsException: 6
	at moe.yushi.authlibinjector.internal.org.objectweb.asm.ClassReader.readShort(ClassReader.java:3608)
	at moe.yushi.authlibinjector.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:197)
	at moe.yushi.authlibinjector.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at moe.yushi.authlibinjector.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at moe.yushi.authlibinjector.transform.ClassTransformer$TransformHandle.getClassReader(ClassTransformer.java:112)
	at moe.yushi.authlibinjector.transform.ClassTransformer$TransformHandle.getStringConstants(ClassTransformer.java:122)
	at moe.yushi.authlibinjector.transform.ClassTransformer$TransformHandle.access$200(ClassTransformer.java:48)
	at moe.yushi.authlibinjector.transform.ClassTransformer$TransformHandle$TransformContextImpl.getStringConstants(ClassTransformer.java:89)
	at moe.yushi.authlibinjector.transform.support.UsernameCharacterCheckTransformer.transform(UsernameCharacterCheckTransformer.java:34)
	at moe.yushi.authlibinjector.transform.ClassTransformer$TransformHandle.accept(ClassTransformer.java:135)
	at moe.yushi.authlibinjector.transform.ClassTransformer.transform(ClassTransformer.java:243)
	at sun.instrument.TransformerManager.transform(Unknown Source)
	at sun.instrument.InstrumentationImpl.transform(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.ClassFormatError: Truncated class file
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.forName0(Native Method)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.forName(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	Suppressed: java.io.IOException: CRC error while extracting entry from JAR file
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 		at sun.misc.URLClassPath$JarLoader$2.getBytes(Unknown Source)
[14:42:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 		... 16 more
Exception in thread "main" 
```

**System Information**
 - OS: Windows 11 25145.1000
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: 4.2.1

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
-CustomSkinLoader_Forge-14.11

**Additional info**
<Add any other context about the problem here.>

**Comment by HarcicYang** [comment]
I tried to remove CustomSkinLoader, but Minecraft can't launch either.

**Comment by DinoFengz** [comment]
use github actions or release not fdploader

**Comment by HarcicYang** [comment]
Oh, thanks
